dist: trusty
sudo: required

language: go
go:
  - 1.12.7

services:
  - docker

jobs:
  include:
    - stage: test
      arch: amd64
      script: make coverage
    - stage: test
      arch: arm64
      script: make coverage
    - stage: integrate
      arch: amd64
      script: make integrate
    - stage: integrate
      arch: arm64
      script: make integrate
    - stage: build
      arch: amd64
      script: make build
    - stage: build
      arch: arm64
      script: make build
#    - stage: deploy
#    - stage: release


stages:
  - name: test
  - name: integrate
  - name: build
#    if: branch = master
#  - name: deploy
#    if: branch = master

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - junxiong.sjx@antfin.com
    - lingtao.klt@antfin.com
    - linzhengchun.lzc@alibaba-inc.com
    - xiaojian.aoxiaojia@antfin.com
    - xiaodong.dxd@antfin.com
